#!/bin/bash
if [ $# -lt 1 ]; then
    echo dapk .apk
    exit 1
fi
file=$1
name=${file##*/}
name=${name%.*}
name=dapk.out/$name
source=$name-dex2jar.jar

echo [dapk] start ...
apktool -o $name.apktool d $file
unzip -od $name.unzip $file
d2j-dex2jar.sh -d -o $source $name.unzip/classes.dex
java -jar apk/jd-gui-1.4.0.jar $source
echo [dapk] done
