#!/bin/bash 
NAME=local_dev

start() {
    if [ ! "$(docker ps -q -f name=$NAME)" ]; then
        if [ ! "$(docker ps -aq -f status=exited -f name=$NAME)" ]; then
            # --privileged选项，命令/usr/sbin/init，才能使用systemctl (-v /Users/lvshaco:/root/share:ro只读）
            echo run 1234
            #docker run -itd -w /root -v /Users/lvshaco:/root/share --name local_dev --privileged centos:centos7.9.2009 /usr/sbin/init
            # 上面的无效了，使用下面普通的，然后使用systemctl.py替代系统的systemctl
            docker run -itd -w /root -v /Users/lvshaco:/root/share --name local_dev centos:centos7.9.2009 /bin/bash
        else
            echo exist already
            docker start $NAME
        fi
	fi
}

stop() {
    docker stop -t 0 $NAME
}

login() {
    start
    # 中文乱码
    # env LANG=C.UTF-8
    # 安装localedef -v -c -i en_US -f UTF-8 C.UTF-8
    docker exec -w /root -it $NAME env LANG=zh_CN.UTF-8 /bin/bash
    #docker exec -w /root -it $NAME /bin/bash
}

cmd=$1
shift
case $cmd in
    start) 		start;;
	stop)		stop;;
	login)		login;;
    *) echo "Usage: $0 start|stop|login";;
esac
