#!/bin/bash 
NAME=local_dev1

start() {
    if [ ! "$(docker ps -q -f name=$NAME)" ]; then
        if [ ! "$(docker ps -aq -f status=exited -f name=$NAME)" ]; then
            # --privileged选项，命令/usr/sbin/init，才能使用systemctl (-v /Users/lvshaco:/root/share:ro只读）
            #docker run -itd -w /root -v /Users/lvshaco:/root/share --name local_dev1 --privileged lvsgame/centos:latest /usr/sbin/init
            #
            # 上面的无效了，使用下面普通的，然后使用systemctl.py替代系统的systemctl
            # docker run -itd -w /root -v /Users/lvshaco/dev:/root/dev --name local_dev1 -p 18001:18001 -p 18101:18101 -p 3306:3306 lvsgame/centos7:latest /bin/bash

            # 需要分配固定ip
            # docker network create --subnet=172.18.0.0/16 mynetwork
            # docker run -itd --name XXX --net mynetwork --ip 172.18.0.2 centos:latest /bin/bash
            docker run -itd -w /root -v /Users/lvshaco/dev:/root/dev --name local_dev1 --cap-add SYS_TIME --net mynetwork --ip 172.18.0.2 lvsgame/centos7:latest /bin/bash
        else
            docker start $NAME
        fi
	fi
}

stop() {
    docker stop -t 0 $NAME
}

login() {
    start
    # 中文乱码
    # env LANG=C.UTF-8
    # 安装localedef -v -c -i en_US -f UTF-8 C.UTF-8
    docker exec -w /root -it $NAME env LANG=zh_CN.UTF-8 /bin/bash
    #docker exec -w /root -it $NAME /bin/bash
}

cmd=$1
shift
case $cmd in
    start) 		start;;
	stop)		stop;;
	login)		login;;
    *) echo "Usage: $0 start|stop|login";;
esac
