#!/bin/bash 
NAME=local_dev

start() {
    if [ ! "$(docker ps -q -f name=$NAME)" ]; then
        if [ ! "$(docker ps -aq -f status=exited -f name=$NAME)" ]; then
            # --privileged选项，命令/usr/sbin/init，才能使用systemctl (-v /Users/lvshaco:/root/share:ro只读）
            docker run -itd -w /root -v /Users/lvshaco:/root/share --name local_dev --privileged lvsgame/centos7 /usr/sbin/init
        else
            docker start $NAME
        fi
	fi
}

stop() {
    docker stop $NAME
}

login() {
    start
    docker exec -w /root -it $NAME /bin/bash
}

cmd=$1
shift
case $cmd in
    start) 		start;;
	stop)		stop;;
	login)		login;;
    *) echo "Usage: $0 start|stop|login";;
esac
