#!/bin/bash
dir=$(cd $(dirname $BASH_SOURCE) && pwd)
cmd=$1
shift
case $cmd in
	mount) sshfs local_dev:/home/lxj/lddz ~/lddz;;
	client) scp local_dev:~/protocol.proto local_dev:~/error.lua ~;;
    user_count) ssh lddz_hulu "./util.sh user_count" ;;
    room_count) ssh lddz_hulu "./util.sh room_count" ;;
    edit) vim $dir/lddz;;
    ci) cd $dir && git commit -a -m "fix" && git push;;
    *) echo unkown command;;
esac
