#!/bin/bash

gm_score() {
    echo $1
    D=$1 #`date '+%Y%m%d'`
    ssh lddz_hulu "./test.sh gm_score $D,$D"
}

dir=$(cd $(dirname $BASH_SOURCE) && pwd)
cmd=$1
shift
case $cmd in
	mount) sshfs local_dev:/home/lxj/code/guandan ~/guandan;;
	client) scp local_dev:~/protocol.proto \
        local_dev:~/protocolInfo.lua \
        local_dev:~/error.lua \
        local_dev:~/recharge.json \
        local_dev:~/*.md \
        ~;;
    user_count) ssh lddz_hulu "./util.sh user_count" ;;
    room_count) ssh lddz_hulu "./util.sh room_count" ;;
    edit) vim $dir/lddz;;
    ci) cd $dir && git commit -a -m "fix" && git push;;
    gm_score) gm_score $1;;
    push_res) scp -r ~/gouji-plan/res/xlsx local_dev:code/guandan/res/;;
    pull_res) scp -r local_dev:code/guandan/res/xlsx ~/gouji-plan/res/;;
    up_res) cd ~/gouji-plan/res && svn up && cd - && lddz push_res && ssh local_dev "cd code/guandan/ && make res && ./dist.sh dist";;
    *) echo unkown command;;
esac
