#!/bin/bash 
dir=$(cd $(dirname $BASH_SOURCE) && pwd)
cmd=$1
shift
case $cmd in
    fanyi) cd $dir && ./fanyi $@;;
    ctime) python -c "import time; print time.ctime($@)";;
	mount_ddz) sshfs local_dev:/home/lxj/lddz ~/lddz;;
    pass) cat ~/Dropbox/pass;;
    edit) vim $dir/lfoot;;
    ci) cd $dir && git commit -a -m "$1" && git push;;
    hulu) ssh lddz_hulu "./util.sh user_count; ./util.sh room_count";;
    *) echo unkown command;;
esac
