#!/bin/bash

usage() {
    cat << EOF
Usage: $0 cmd
体脂率:     $0 BFR 体重(公斤) 腰围(厘米)
体质指数:   $0 BMI 体重(公斤) 身高(米)
EOF
}

dir=$(cd $(dirname $BASH_SOURCE) && pwd)
cmd=$1
shift
case $cmd in
    fanyi) cd $dir && ./fanyi $@;;
    ctime) python -c "
import time;
timeArray = time.localtime($@);
print time.strftime('%Y%m%d %H:%M:%S',timeArray);
";;
    time) python -c "
import time
import datetime
d = datetime.datetime.strptime('$@', '%Y%m%d %H:%M:%S')
t = d.timetuple()
timeStamp = int(time.mktime(t))
print(timeStamp)
";;
    pass) cat ~/Dropbox/pass;;
    edit) vim $dir/lfoot;;
    ci) cd $dir && git commit -a -m "update" && git push;;
    hulu) ssh lddz_hulu "./util.sh user_count; ./util.sh room_count";;
    BFR) echo "scale=3; (($2*0.74) - ($1 * 0.082 + 44.74)) / $1" | bc;;
    BMI) echo "scale=3; $1 / ($2*$2)" | bc;;
    start_web) nginx && php-fpm;;
    ssh_config) scp local_dev:~/.ssh/config config.local_dev; cp ~/.ssh/config config.local;;
    *) usage;;
esac
