#!/bin/bash
dir=`dirname "$0"`

name=centos7-systemd

pull() {
	cd "$dir" &&
	docker build --rm -t $name -f ./docker/$name.Dockerfile docker
}

start() {
	docker ps -a |grep "\<$name\>"
	if [ $? -ne 0 ]; then
		# systemd无法工作，所以使用centos7-systemd.Dockerfile创建镜像，并使用此命令创建容器
		docker run -d --cap-add SYS_ADMIN --name $name \
			-v/Users/lvshaco/Downloads:/Downloads -v/Users/lvshaco/code:/Code \
			$name /sbin/init
		#docker run -it --name $name \
		#	-v/Users/lvshaco/Downloads:/Downloads -v/Users/lvshaco/code:/Code \
		#	centos bin/bash
	else
		docker start $name
	fi
}

stop() {
	docker ps -a |grep "\<$name\>" |grep Up
	if [ $? -eq 0 ]; then
		docker stop $name
	fi
}

exec() {
	docker ps -a |grep "\<$name\>" |grep Up
	if [ $? -ne 0 ]; then
		start
	else
		docker exec -it $name bash
	fi
}

cmd=$1
shift
case $cmd in
	pull)  pull;;
	start) start;;
	stop)  stop;;
	exec)  exec;;
	ps)    docker ps $@;;
	*) 	   echo unknown command ;;
esac
